databases:
  - name: tax-sale-db
    plan:  free

services:
  - type: web
    name: tax-sale-web
    runtime: ruby
    plan: starter
    buildCommand: "bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate"
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: GOOGLE_SHEETS_SHEET_ID
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: tax-sale-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: tax-sale-redis
          property: connectionString

  - type: worker
    name: tax-sale-worker
    runtime: ruby
    plan: starter
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tax-sale-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: tax-sale-redis
          property: connectionString

  - type: redis
    name: tax-sale-redis
    plan: starter
    ipAllowList: []
    maxmemoryPolicy: noeviction
