default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: tax_sale_resources_development

test:
  <<: *default
  database: tax_sale_resources_test
  host: localhost
  username: postgres
  password: ""

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
